### ISSUE TITLE
Recipe in NEI for NuclearCraft Empty Reactor Cooler made in NuclearCraft Assembler doesn't work

### ISSUE THREAD

**Issue by otakucode** [BevoTechPack/BevoTechPack#1011]
Bevo Tech Pack Version :- Beta U-NC (updated directly from T to U-NC if that matters)

### Description of issue/bug
In NEI, the crafting recipe for the NC Empty Reactor Cooler built in the NC Assembler is (going left to right, top to bottom): Basic Plating x3, Universal Reactant, Stick, Stick.  That is supposed to craft 4 Empty Reactor Coolers.  Placing those items in the NC Assembler does nothing.  Placing a larger quantity of Basic Plating and Universal Reactant (specifically 5 and 2 respectively) in the Assembler produces 2 Small Nuclear Chambers which matches the recipe for the Small Nuclear Chamber for the Assembler in NEI.  I imagine there must be some sort of conflict due to the only variation between the recipes being quantity of the ingredients.  I do not know if those recipes are NuclearCraft default or not.  I checked the NuclearCraft github Issues tracker and found no mention of this issue.  

### Steps to reproduce the issue/bug
Build a NuclearCraft Assembler, give it power, place 3 Basic Plating in top-left, 1 Universal Reactant in top-right, and 1 vanilla Stick in both bottom slots, watch nothing happen.

Questions:

Did you add any additional mods? - Nope.
Do you use optifine? - Nope.
Did the problem appear in single player or on a server? - Single player.

**Comment by b0bst3r** [comment]
Fixed in BetaV

**Comment by otakucode** [comment]
I just updated from Beta U-NC to Beta V-NC and I still get the exact same behavior.

**Comment by b0bst3r** [comment]
OK I know what's going on you're looking at the normal crafting recipe which shouldn't be happening, are you connected to a server?

**Comment by b0bst3r** [comment]
It's a bug it takes 4 plates even though the recipe shows 3

**Comment by otakucode** [comment]
I'm playing single-player.  I updated via the ATLauncher from U-NC to V-NC.  Should I have updated to V either before or after doing V-NC?  I still get a 'update is available' prompt whenever I launch the instance, but I've been saying 'no' and just continuing with V-NC.  

I managed to get it to craft... but it acts a bit strange.  When I put in 4 Basic Plating and 2 Universal Reactant (along with the sticks), it crafts 4 Empty Reactor Coolers... and leaves 1 Basic Plating and 1 Universal Reactant in the machine.  Maybe this is how the Assembler works and I'm just unfamiliar with it?  So that you always need 1 more of each type of item so that 1 can be left in the machine afterward?

**Comment by turbodiesel4598** [comment]
This is intentional - it's so that the recipe doesn't get removed after the crafting takes place. The idea is that you set a bunch of them up, each with a recipe, and just pipe the correct number of ingredients in when you want to craft something. It's very similar to BuildCraft's auto-workbench in that respect :)

**Comment by b0bst3r** [comment]
No way to leave a ghost image in as you're probably going to get a ton of these and people not know how to craft things?

**Comment by turbodiesel4598** [comment]
Good point - will have to think of the best way of telling the player. The ghost image would be nice but I'm not sure how it would actually work in practice. Perhaps I can have a little warning appear when one more of each material is required, telling the player what they need to do.

**Comment by b0bst3r** [comment]
Closing this as it's not a bug it's how its supposed to be.
