### ISSUE TITLE
Crafting Meks Induction blocks cause crash

### ISSUE THREAD

**Issue by b0bst3r** [BevoTechPack/BevoTechPack#989]
Reviewing Minetweaker scripts

@Sil3ntStorm Have you looked at your scripts?  Both the Induction cell and Induction providers cause crash in the crafting table.

**Comment by b0bst3r** [comment]
Will be fixed in BetaS

**Comment by Sil3ntStorm** [comment]
I'm sorry for not responding, I was on vacation and didn't check emails, let alone had access to any code or Minecraft.

It's kind of funny that you accuse me of not testing my scripts though.

#996 should never have been merged in the first place, as it breaks the script, causing MT to stop processing it. Evidently whoever did those didn't even load Minecraft with the modifications in the first place before putting up that PR, nor were any tests performed before actually merging that PR.

As for this issue, it crashes because you removed code from the script in https://github.com/BevoTechPack/BevoTechPack/commit/171b7e8babba261f9ddb4e28ae05dd343fc827ef#diff-3bc27a836dc8025a25f61f0223e1ba3a and apparently did not test whether that part of the script was actually there on purpose (which it was, because I found the same crash when I was testing my original code).

The only situation in which my original code would cause a crash, would be when old Energy Tablets that were crafted before my original code made it into a public release and that have never been placed in an energy container (ie. never stored any energy) would be used in crafting a Basic Induction Cell. I guess I didn't think anyone would pre-craft Energy Tablets. That I'll take the blame for.

As far as Induction Providers go, I cannot see why they would possibly crash the game with or without the modifications done. That is to say I cannot see how crafting Induction Providers would've crashed the game at any point in recent history. If you can provide me with an example I'll happily take a look though. Would love to understand how they could possibly cause one with any of the modifications.

The reason for the crash itself is that my original code, just like original Mekanism and unlike the current modification in the repository, maintains the energy present in any of the energy accepting / storing items when using these to craft a new item. Mekanism tries to be efficient and only stores the energy information on the Energy Tablets at the moment an Energy Tablet stores energy for the first time. This wouldn't be an issue if MineTweaker were to check for data to be present before accessing the data, but since MT does not seem to perform these checks (and seems to either have a bug that prevents you checking for yourself or I have yet to find a working variant) it will end up attempting to perform additions with non-numeric values, which ultimately crashes the game.

**Comment by b0bst3r** [comment]
Woah nelly I didn't accuse you of testing anything, I updated Mekanism from V8 to V9 and they broke, they are fixed and working now. :)

**Comment by Sil3ntStorm** [comment]
It does seem as though Mekanism 9 will craft the Tablets with NBT Tags now by default, so the lines fixing the Tablets indeed don't seem to be necessary anymore.
Still don't see why it would crash when regularly crafting induction components. Of course it will cause a crash when the components were cheated in using NEI as NEI won't add NBT data.
Did download and put latest Mekanism in, without crash.
